// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Appointment is the predicate function for appointment builders.
type Appointment func(*sql.Selector)

// Certification is the predicate function for certification builders.
type Certification func(*sql.Selector)

// Chat is the predicate function for chat builders.
type Chat func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Disease is the predicate function for disease builders.
type Disease func(*sql.Selector)

// Hospital is the predicate function for hospital builders.
type Hospital func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// PInfo is the predicate function for pinfo builders.
type PInfo func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Schedule is the predicate function for schedule builders.
type Schedule func(*sql.Selector)

// Telecom is the predicate function for telecom builders.
type Telecom func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// Treatment is the predicate function for treatment builders.
type Treatment func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
