// Code generated by entc, DO NOT EDIT.

package ent

import (
	"FinalProject/ent/predicate"
	"FinalProject/ent/schedule"
	"FinalProject/ent/scheduletime"
	"FinalProject/ent/user"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScheduleUpdate is the builder for updating Schedule entities.
type ScheduleUpdate struct {
	config
	hooks    []Hook
	mutation *ScheduleMutation
}

// Where appends a list predicates to the ScheduleUpdate builder.
func (su *ScheduleUpdate) Where(ps ...predicate.Schedule) *ScheduleUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetActivity sets the "activity" field.
func (su *ScheduleUpdate) SetActivity(s string) *ScheduleUpdate {
	su.mutation.SetActivity(s)
	return su
}

// SetDetail sets the "detail" field.
func (su *ScheduleUpdate) SetDetail(s string) *ScheduleUpdate {
	su.mutation.SetDetail(s)
	return su
}

// SetStatus sets the "status" field.
func (su *ScheduleUpdate) SetStatus(s string) *ScheduleUpdate {
	su.mutation.SetStatus(s)
	return su
}

// AddTimeScheduleIDs adds the "time_schedule" edge to the ScheduleTime entity by IDs.
func (su *ScheduleUpdate) AddTimeScheduleIDs(ids ...int) *ScheduleUpdate {
	su.mutation.AddTimeScheduleIDs(ids...)
	return su
}

// AddTimeSchedule adds the "time_schedule" edges to the ScheduleTime entity.
func (su *ScheduleUpdate) AddTimeSchedule(s ...*ScheduleTime) *ScheduleUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddTimeScheduleIDs(ids...)
}

// SetWhoIsTheOwnerOfThisScheduleID sets the "who_is_the_owner_of_this_schedule" edge to the User entity by ID.
func (su *ScheduleUpdate) SetWhoIsTheOwnerOfThisScheduleID(id int) *ScheduleUpdate {
	su.mutation.SetWhoIsTheOwnerOfThisScheduleID(id)
	return su
}

// SetNillableWhoIsTheOwnerOfThisScheduleID sets the "who_is_the_owner_of_this_schedule" edge to the User entity by ID if the given value is not nil.
func (su *ScheduleUpdate) SetNillableWhoIsTheOwnerOfThisScheduleID(id *int) *ScheduleUpdate {
	if id != nil {
		su = su.SetWhoIsTheOwnerOfThisScheduleID(*id)
	}
	return su
}

// SetWhoIsTheOwnerOfThisSchedule sets the "who_is_the_owner_of_this_schedule" edge to the User entity.
func (su *ScheduleUpdate) SetWhoIsTheOwnerOfThisSchedule(u *User) *ScheduleUpdate {
	return su.SetWhoIsTheOwnerOfThisScheduleID(u.ID)
}

// Mutation returns the ScheduleMutation object of the builder.
func (su *ScheduleUpdate) Mutation() *ScheduleMutation {
	return su.mutation
}

// ClearTimeSchedule clears all "time_schedule" edges to the ScheduleTime entity.
func (su *ScheduleUpdate) ClearTimeSchedule() *ScheduleUpdate {
	su.mutation.ClearTimeSchedule()
	return su
}

// RemoveTimeScheduleIDs removes the "time_schedule" edge to ScheduleTime entities by IDs.
func (su *ScheduleUpdate) RemoveTimeScheduleIDs(ids ...int) *ScheduleUpdate {
	su.mutation.RemoveTimeScheduleIDs(ids...)
	return su
}

// RemoveTimeSchedule removes "time_schedule" edges to ScheduleTime entities.
func (su *ScheduleUpdate) RemoveTimeSchedule(s ...*ScheduleTime) *ScheduleUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveTimeScheduleIDs(ids...)
}

// ClearWhoIsTheOwnerOfThisSchedule clears the "who_is_the_owner_of_this_schedule" edge to the User entity.
func (su *ScheduleUpdate) ClearWhoIsTheOwnerOfThisSchedule() *ScheduleUpdate {
	su.mutation.ClearWhoIsTheOwnerOfThisSchedule()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *ScheduleUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		if err = su.check(); err != nil {
			return 0, err
		}
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScheduleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = su.check(); err != nil {
				return 0, err
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *ScheduleUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ScheduleUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ScheduleUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *ScheduleUpdate) check() error {
	if v, ok := su.mutation.Status(); ok {
		if err := schedule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf("ent: validator failed for field \"status\": %w", err)}
		}
	}
	return nil
}

func (su *ScheduleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   schedule.Table,
			Columns: schedule.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: schedule.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Activity(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: schedule.FieldActivity,
		})
	}
	if value, ok := su.mutation.Detail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: schedule.FieldDetail,
		})
	}
	if value, ok := su.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: schedule.FieldStatus,
		})
	}
	if su.mutation.TimeScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schedule.TimeScheduleTable,
			Columns: []string{schedule.TimeScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scheduletime.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedTimeScheduleIDs(); len(nodes) > 0 && !su.mutation.TimeScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schedule.TimeScheduleTable,
			Columns: []string{schedule.TimeScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scheduletime.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.TimeScheduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schedule.TimeScheduleTable,
			Columns: []string{schedule.TimeScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scheduletime.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.WhoIsTheOwnerOfThisScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.WhoIsTheOwnerOfThisScheduleTable,
			Columns: []string{schedule.WhoIsTheOwnerOfThisScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.WhoIsTheOwnerOfThisScheduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.WhoIsTheOwnerOfThisScheduleTable,
			Columns: []string{schedule.WhoIsTheOwnerOfThisScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// ScheduleUpdateOne is the builder for updating a single Schedule entity.
type ScheduleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScheduleMutation
}

// SetActivity sets the "activity" field.
func (suo *ScheduleUpdateOne) SetActivity(s string) *ScheduleUpdateOne {
	suo.mutation.SetActivity(s)
	return suo
}

// SetDetail sets the "detail" field.
func (suo *ScheduleUpdateOne) SetDetail(s string) *ScheduleUpdateOne {
	suo.mutation.SetDetail(s)
	return suo
}

// SetStatus sets the "status" field.
func (suo *ScheduleUpdateOne) SetStatus(s string) *ScheduleUpdateOne {
	suo.mutation.SetStatus(s)
	return suo
}

// AddTimeScheduleIDs adds the "time_schedule" edge to the ScheduleTime entity by IDs.
func (suo *ScheduleUpdateOne) AddTimeScheduleIDs(ids ...int) *ScheduleUpdateOne {
	suo.mutation.AddTimeScheduleIDs(ids...)
	return suo
}

// AddTimeSchedule adds the "time_schedule" edges to the ScheduleTime entity.
func (suo *ScheduleUpdateOne) AddTimeSchedule(s ...*ScheduleTime) *ScheduleUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddTimeScheduleIDs(ids...)
}

// SetWhoIsTheOwnerOfThisScheduleID sets the "who_is_the_owner_of_this_schedule" edge to the User entity by ID.
func (suo *ScheduleUpdateOne) SetWhoIsTheOwnerOfThisScheduleID(id int) *ScheduleUpdateOne {
	suo.mutation.SetWhoIsTheOwnerOfThisScheduleID(id)
	return suo
}

// SetNillableWhoIsTheOwnerOfThisScheduleID sets the "who_is_the_owner_of_this_schedule" edge to the User entity by ID if the given value is not nil.
func (suo *ScheduleUpdateOne) SetNillableWhoIsTheOwnerOfThisScheduleID(id *int) *ScheduleUpdateOne {
	if id != nil {
		suo = suo.SetWhoIsTheOwnerOfThisScheduleID(*id)
	}
	return suo
}

// SetWhoIsTheOwnerOfThisSchedule sets the "who_is_the_owner_of_this_schedule" edge to the User entity.
func (suo *ScheduleUpdateOne) SetWhoIsTheOwnerOfThisSchedule(u *User) *ScheduleUpdateOne {
	return suo.SetWhoIsTheOwnerOfThisScheduleID(u.ID)
}

// Mutation returns the ScheduleMutation object of the builder.
func (suo *ScheduleUpdateOne) Mutation() *ScheduleMutation {
	return suo.mutation
}

// ClearTimeSchedule clears all "time_schedule" edges to the ScheduleTime entity.
func (suo *ScheduleUpdateOne) ClearTimeSchedule() *ScheduleUpdateOne {
	suo.mutation.ClearTimeSchedule()
	return suo
}

// RemoveTimeScheduleIDs removes the "time_schedule" edge to ScheduleTime entities by IDs.
func (suo *ScheduleUpdateOne) RemoveTimeScheduleIDs(ids ...int) *ScheduleUpdateOne {
	suo.mutation.RemoveTimeScheduleIDs(ids...)
	return suo
}

// RemoveTimeSchedule removes "time_schedule" edges to ScheduleTime entities.
func (suo *ScheduleUpdateOne) RemoveTimeSchedule(s ...*ScheduleTime) *ScheduleUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveTimeScheduleIDs(ids...)
}

// ClearWhoIsTheOwnerOfThisSchedule clears the "who_is_the_owner_of_this_schedule" edge to the User entity.
func (suo *ScheduleUpdateOne) ClearWhoIsTheOwnerOfThisSchedule() *ScheduleUpdateOne {
	suo.mutation.ClearWhoIsTheOwnerOfThisSchedule()
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *ScheduleUpdateOne) Select(field string, fields ...string) *ScheduleUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Schedule entity.
func (suo *ScheduleUpdateOne) Save(ctx context.Context) (*Schedule, error) {
	var (
		err  error
		node *Schedule
	)
	if len(suo.hooks) == 0 {
		if err = suo.check(); err != nil {
			return nil, err
		}
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScheduleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = suo.check(); err != nil {
				return nil, err
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ScheduleUpdateOne) SaveX(ctx context.Context) *Schedule {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *ScheduleUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ScheduleUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *ScheduleUpdateOne) check() error {
	if v, ok := suo.mutation.Status(); ok {
		if err := schedule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf("ent: validator failed for field \"status\": %w", err)}
		}
	}
	return nil
}

func (suo *ScheduleUpdateOne) sqlSave(ctx context.Context) (_node *Schedule, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   schedule.Table,
			Columns: schedule.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: schedule.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Schedule.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schedule.FieldID)
		for _, f := range fields {
			if !schedule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schedule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Activity(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: schedule.FieldActivity,
		})
	}
	if value, ok := suo.mutation.Detail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: schedule.FieldDetail,
		})
	}
	if value, ok := suo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: schedule.FieldStatus,
		})
	}
	if suo.mutation.TimeScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schedule.TimeScheduleTable,
			Columns: []string{schedule.TimeScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scheduletime.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedTimeScheduleIDs(); len(nodes) > 0 && !suo.mutation.TimeScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schedule.TimeScheduleTable,
			Columns: []string{schedule.TimeScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scheduletime.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.TimeScheduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schedule.TimeScheduleTable,
			Columns: []string{schedule.TimeScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scheduletime.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.WhoIsTheOwnerOfThisScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.WhoIsTheOwnerOfThisScheduleTable,
			Columns: []string{schedule.WhoIsTheOwnerOfThisScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.WhoIsTheOwnerOfThisScheduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.WhoIsTheOwnerOfThisScheduleTable,
			Columns: []string{schedule.WhoIsTheOwnerOfThisScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Schedule{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
