// Code generated by entc, DO NOT EDIT.

package ent

import (
	"FinalProject/ent/certification"
	"FinalProject/ent/chat"
	"FinalProject/ent/department"
	"FinalProject/ent/disease"
	"FinalProject/ent/hospital"
	"FinalProject/ent/message"
	"FinalProject/ent/notification"
	"FinalProject/ent/pinfo"
	"FinalProject/ent/predicate"
	"FinalProject/ent/role"
	"FinalProject/ent/schedule"
	"FinalProject/ent/telecom"
	"FinalProject/ent/token"
	"FinalProject/ent/treatment"
	"FinalProject/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetUsername sets the "username" field.
func (uu *UserUpdate) SetUsername(s string) *UserUpdate {
	uu.mutation.SetUsername(s)
	return uu
}

// SetPassword sets the "password" field.
func (uu *UserUpdate) SetPassword(s string) *UserUpdate {
	uu.mutation.SetPassword(s)
	return uu
}

// AddDoctorHasCertificationIDs adds the "doctor_has_certification" edge to the Certification entity by IDs.
func (uu *UserUpdate) AddDoctorHasCertificationIDs(ids ...int) *UserUpdate {
	uu.mutation.AddDoctorHasCertificationIDs(ids...)
	return uu
}

// AddDoctorHasCertification adds the "doctor_has_certification" edges to the Certification entity.
func (uu *UserUpdate) AddDoctorHasCertification(c ...*Certification) *UserUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uu.AddDoctorHasCertificationIDs(ids...)
}

// AddUserHasPInfoIDs adds the "user_has_PInfo" edge to the PInfo entity by IDs.
func (uu *UserUpdate) AddUserHasPInfoIDs(ids ...int) *UserUpdate {
	uu.mutation.AddUserHasPInfoIDs(ids...)
	return uu
}

// AddUserHasPInfo adds the "user_has_PInfo" edges to the PInfo entity.
func (uu *UserUpdate) AddUserHasPInfo(p ...*PInfo) *UserUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uu.AddUserHasPInfoIDs(ids...)
}

// AddDoctorScheduleIDs adds the "doctor_schedule" edge to the Schedule entity by IDs.
func (uu *UserUpdate) AddDoctorScheduleIDs(ids ...int) *UserUpdate {
	uu.mutation.AddDoctorScheduleIDs(ids...)
	return uu
}

// AddDoctorSchedule adds the "doctor_schedule" edges to the Schedule entity.
func (uu *UserUpdate) AddDoctorSchedule(s ...*Schedule) *UserUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return uu.AddDoctorScheduleIDs(ids...)
}

// AddUserHaveTelecomIDs adds the "user_have_telecoms" edge to the Telecom entity by IDs.
func (uu *UserUpdate) AddUserHaveTelecomIDs(ids ...int) *UserUpdate {
	uu.mutation.AddUserHaveTelecomIDs(ids...)
	return uu
}

// AddUserHaveTelecoms adds the "user_have_telecoms" edges to the Telecom entity.
func (uu *UserUpdate) AddUserHaveTelecoms(t ...*Telecom) *UserUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uu.AddUserHaveTelecomIDs(ids...)
}

// AddDoctorRecordTreatmentIDs adds the "doctor_record_treatment" edge to the Treatment entity by IDs.
func (uu *UserUpdate) AddDoctorRecordTreatmentIDs(ids ...int) *UserUpdate {
	uu.mutation.AddDoctorRecordTreatmentIDs(ids...)
	return uu
}

// AddDoctorRecordTreatment adds the "doctor_record_treatment" edges to the Treatment entity.
func (uu *UserUpdate) AddDoctorRecordTreatment(t ...*Treatment) *UserUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uu.AddDoctorRecordTreatmentIDs(ids...)
}

// AddUserHaveTreatmentIDs adds the "user_have_treatment" edge to the Treatment entity by IDs.
func (uu *UserUpdate) AddUserHaveTreatmentIDs(ids ...int) *UserUpdate {
	uu.mutation.AddUserHaveTreatmentIDs(ids...)
	return uu
}

// AddUserHaveTreatment adds the "user_have_treatment" edges to the Treatment entity.
func (uu *UserUpdate) AddUserHaveTreatment(t ...*Treatment) *UserUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uu.AddUserHaveTreatmentIDs(ids...)
}

// AddUserHaveTokenIDs adds the "user_have_token" edge to the Token entity by IDs.
func (uu *UserUpdate) AddUserHaveTokenIDs(ids ...int) *UserUpdate {
	uu.mutation.AddUserHaveTokenIDs(ids...)
	return uu
}

// AddUserHaveToken adds the "user_have_token" edges to the Token entity.
func (uu *UserUpdate) AddUserHaveToken(t ...*Token) *UserUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uu.AddUserHaveTokenIDs(ids...)
}

// AddUserSendMessageIDs adds the "user_send_message" edge to the Message entity by IDs.
func (uu *UserUpdate) AddUserSendMessageIDs(ids ...int) *UserUpdate {
	uu.mutation.AddUserSendMessageIDs(ids...)
	return uu
}

// AddUserSendMessage adds the "user_send_message" edges to the Message entity.
func (uu *UserUpdate) AddUserSendMessage(m ...*Message) *UserUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return uu.AddUserSendMessageIDs(ids...)
}

// AddUserSendNotificationIDs adds the "user_send_notification" edge to the Notification entity by IDs.
func (uu *UserUpdate) AddUserSendNotificationIDs(ids ...int) *UserUpdate {
	uu.mutation.AddUserSendNotificationIDs(ids...)
	return uu
}

// AddUserSendNotification adds the "user_send_notification" edges to the Notification entity.
func (uu *UserUpdate) AddUserSendNotification(n ...*Notification) *UserUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return uu.AddUserSendNotificationIDs(ids...)
}

// SetHasDepartmentID sets the "has_department" edge to the Department entity by ID.
func (uu *UserUpdate) SetHasDepartmentID(id int) *UserUpdate {
	uu.mutation.SetHasDepartmentID(id)
	return uu
}

// SetNillableHasDepartmentID sets the "has_department" edge to the Department entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableHasDepartmentID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetHasDepartmentID(*id)
	}
	return uu
}

// SetHasDepartment sets the "has_department" edge to the Department entity.
func (uu *UserUpdate) SetHasDepartment(d *Department) *UserUpdate {
	return uu.SetHasDepartmentID(d.ID)
}

// SetFromHospitalID sets the "from_hospital" edge to the Hospital entity by ID.
func (uu *UserUpdate) SetFromHospitalID(id int) *UserUpdate {
	uu.mutation.SetFromHospitalID(id)
	return uu
}

// SetNillableFromHospitalID sets the "from_hospital" edge to the Hospital entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableFromHospitalID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetFromHospitalID(*id)
	}
	return uu
}

// SetFromHospital sets the "from_hospital" edge to the Hospital entity.
func (uu *UserUpdate) SetFromHospital(h *Hospital) *UserUpdate {
	return uu.SetFromHospitalID(h.ID)
}

// AddUserHaveDiseaseIDs adds the "user_have_disease" edge to the Disease entity by IDs.
func (uu *UserUpdate) AddUserHaveDiseaseIDs(ids ...int) *UserUpdate {
	uu.mutation.AddUserHaveDiseaseIDs(ids...)
	return uu
}

// AddUserHaveDisease adds the "user_have_disease" edges to the Disease entity.
func (uu *UserUpdate) AddUserHaveDisease(d ...*Disease) *UserUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return uu.AddUserHaveDiseaseIDs(ids...)
}

// AddUserHaveRoleIDs adds the "user_have_role" edge to the Role entity by IDs.
func (uu *UserUpdate) AddUserHaveRoleIDs(ids ...int) *UserUpdate {
	uu.mutation.AddUserHaveRoleIDs(ids...)
	return uu
}

// AddUserHaveRole adds the "user_have_role" edges to the Role entity.
func (uu *UserUpdate) AddUserHaveRole(r ...*Role) *UserUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uu.AddUserHaveRoleIDs(ids...)
}

// AddWhoIsInThisChatIDs adds the "who_is_in_this_chat" edge to the Chat entity by IDs.
func (uu *UserUpdate) AddWhoIsInThisChatIDs(ids ...int) *UserUpdate {
	uu.mutation.AddWhoIsInThisChatIDs(ids...)
	return uu
}

// AddWhoIsInThisChat adds the "who_is_in_this_chat" edges to the Chat entity.
func (uu *UserUpdate) AddWhoIsInThisChat(c ...*Chat) *UserUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uu.AddWhoIsInThisChatIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearDoctorHasCertification clears all "doctor_has_certification" edges to the Certification entity.
func (uu *UserUpdate) ClearDoctorHasCertification() *UserUpdate {
	uu.mutation.ClearDoctorHasCertification()
	return uu
}

// RemoveDoctorHasCertificationIDs removes the "doctor_has_certification" edge to Certification entities by IDs.
func (uu *UserUpdate) RemoveDoctorHasCertificationIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveDoctorHasCertificationIDs(ids...)
	return uu
}

// RemoveDoctorHasCertification removes "doctor_has_certification" edges to Certification entities.
func (uu *UserUpdate) RemoveDoctorHasCertification(c ...*Certification) *UserUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uu.RemoveDoctorHasCertificationIDs(ids...)
}

// ClearUserHasPInfo clears all "user_has_PInfo" edges to the PInfo entity.
func (uu *UserUpdate) ClearUserHasPInfo() *UserUpdate {
	uu.mutation.ClearUserHasPInfo()
	return uu
}

// RemoveUserHasPInfoIDs removes the "user_has_PInfo" edge to PInfo entities by IDs.
func (uu *UserUpdate) RemoveUserHasPInfoIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveUserHasPInfoIDs(ids...)
	return uu
}

// RemoveUserHasPInfo removes "user_has_PInfo" edges to PInfo entities.
func (uu *UserUpdate) RemoveUserHasPInfo(p ...*PInfo) *UserUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uu.RemoveUserHasPInfoIDs(ids...)
}

// ClearDoctorSchedule clears all "doctor_schedule" edges to the Schedule entity.
func (uu *UserUpdate) ClearDoctorSchedule() *UserUpdate {
	uu.mutation.ClearDoctorSchedule()
	return uu
}

// RemoveDoctorScheduleIDs removes the "doctor_schedule" edge to Schedule entities by IDs.
func (uu *UserUpdate) RemoveDoctorScheduleIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveDoctorScheduleIDs(ids...)
	return uu
}

// RemoveDoctorSchedule removes "doctor_schedule" edges to Schedule entities.
func (uu *UserUpdate) RemoveDoctorSchedule(s ...*Schedule) *UserUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return uu.RemoveDoctorScheduleIDs(ids...)
}

// ClearUserHaveTelecoms clears all "user_have_telecoms" edges to the Telecom entity.
func (uu *UserUpdate) ClearUserHaveTelecoms() *UserUpdate {
	uu.mutation.ClearUserHaveTelecoms()
	return uu
}

// RemoveUserHaveTelecomIDs removes the "user_have_telecoms" edge to Telecom entities by IDs.
func (uu *UserUpdate) RemoveUserHaveTelecomIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveUserHaveTelecomIDs(ids...)
	return uu
}

// RemoveUserHaveTelecoms removes "user_have_telecoms" edges to Telecom entities.
func (uu *UserUpdate) RemoveUserHaveTelecoms(t ...*Telecom) *UserUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uu.RemoveUserHaveTelecomIDs(ids...)
}

// ClearDoctorRecordTreatment clears all "doctor_record_treatment" edges to the Treatment entity.
func (uu *UserUpdate) ClearDoctorRecordTreatment() *UserUpdate {
	uu.mutation.ClearDoctorRecordTreatment()
	return uu
}

// RemoveDoctorRecordTreatmentIDs removes the "doctor_record_treatment" edge to Treatment entities by IDs.
func (uu *UserUpdate) RemoveDoctorRecordTreatmentIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveDoctorRecordTreatmentIDs(ids...)
	return uu
}

// RemoveDoctorRecordTreatment removes "doctor_record_treatment" edges to Treatment entities.
func (uu *UserUpdate) RemoveDoctorRecordTreatment(t ...*Treatment) *UserUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uu.RemoveDoctorRecordTreatmentIDs(ids...)
}

// ClearUserHaveTreatment clears all "user_have_treatment" edges to the Treatment entity.
func (uu *UserUpdate) ClearUserHaveTreatment() *UserUpdate {
	uu.mutation.ClearUserHaveTreatment()
	return uu
}

// RemoveUserHaveTreatmentIDs removes the "user_have_treatment" edge to Treatment entities by IDs.
func (uu *UserUpdate) RemoveUserHaveTreatmentIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveUserHaveTreatmentIDs(ids...)
	return uu
}

// RemoveUserHaveTreatment removes "user_have_treatment" edges to Treatment entities.
func (uu *UserUpdate) RemoveUserHaveTreatment(t ...*Treatment) *UserUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uu.RemoveUserHaveTreatmentIDs(ids...)
}

// ClearUserHaveToken clears all "user_have_token" edges to the Token entity.
func (uu *UserUpdate) ClearUserHaveToken() *UserUpdate {
	uu.mutation.ClearUserHaveToken()
	return uu
}

// RemoveUserHaveTokenIDs removes the "user_have_token" edge to Token entities by IDs.
func (uu *UserUpdate) RemoveUserHaveTokenIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveUserHaveTokenIDs(ids...)
	return uu
}

// RemoveUserHaveToken removes "user_have_token" edges to Token entities.
func (uu *UserUpdate) RemoveUserHaveToken(t ...*Token) *UserUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uu.RemoveUserHaveTokenIDs(ids...)
}

// ClearUserSendMessage clears all "user_send_message" edges to the Message entity.
func (uu *UserUpdate) ClearUserSendMessage() *UserUpdate {
	uu.mutation.ClearUserSendMessage()
	return uu
}

// RemoveUserSendMessageIDs removes the "user_send_message" edge to Message entities by IDs.
func (uu *UserUpdate) RemoveUserSendMessageIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveUserSendMessageIDs(ids...)
	return uu
}

// RemoveUserSendMessage removes "user_send_message" edges to Message entities.
func (uu *UserUpdate) RemoveUserSendMessage(m ...*Message) *UserUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return uu.RemoveUserSendMessageIDs(ids...)
}

// ClearUserSendNotification clears all "user_send_notification" edges to the Notification entity.
func (uu *UserUpdate) ClearUserSendNotification() *UserUpdate {
	uu.mutation.ClearUserSendNotification()
	return uu
}

// RemoveUserSendNotificationIDs removes the "user_send_notification" edge to Notification entities by IDs.
func (uu *UserUpdate) RemoveUserSendNotificationIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveUserSendNotificationIDs(ids...)
	return uu
}

// RemoveUserSendNotification removes "user_send_notification" edges to Notification entities.
func (uu *UserUpdate) RemoveUserSendNotification(n ...*Notification) *UserUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return uu.RemoveUserSendNotificationIDs(ids...)
}

// ClearHasDepartment clears the "has_department" edge to the Department entity.
func (uu *UserUpdate) ClearHasDepartment() *UserUpdate {
	uu.mutation.ClearHasDepartment()
	return uu
}

// ClearFromHospital clears the "from_hospital" edge to the Hospital entity.
func (uu *UserUpdate) ClearFromHospital() *UserUpdate {
	uu.mutation.ClearFromHospital()
	return uu
}

// ClearUserHaveDisease clears all "user_have_disease" edges to the Disease entity.
func (uu *UserUpdate) ClearUserHaveDisease() *UserUpdate {
	uu.mutation.ClearUserHaveDisease()
	return uu
}

// RemoveUserHaveDiseaseIDs removes the "user_have_disease" edge to Disease entities by IDs.
func (uu *UserUpdate) RemoveUserHaveDiseaseIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveUserHaveDiseaseIDs(ids...)
	return uu
}

// RemoveUserHaveDisease removes "user_have_disease" edges to Disease entities.
func (uu *UserUpdate) RemoveUserHaveDisease(d ...*Disease) *UserUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return uu.RemoveUserHaveDiseaseIDs(ids...)
}

// ClearUserHaveRole clears all "user_have_role" edges to the Role entity.
func (uu *UserUpdate) ClearUserHaveRole() *UserUpdate {
	uu.mutation.ClearUserHaveRole()
	return uu
}

// RemoveUserHaveRoleIDs removes the "user_have_role" edge to Role entities by IDs.
func (uu *UserUpdate) RemoveUserHaveRoleIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveUserHaveRoleIDs(ids...)
	return uu
}

// RemoveUserHaveRole removes "user_have_role" edges to Role entities.
func (uu *UserUpdate) RemoveUserHaveRole(r ...*Role) *UserUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uu.RemoveUserHaveRoleIDs(ids...)
}

// ClearWhoIsInThisChat clears all "who_is_in_this_chat" edges to the Chat entity.
func (uu *UserUpdate) ClearWhoIsInThisChat() *UserUpdate {
	uu.mutation.ClearWhoIsInThisChat()
	return uu
}

// RemoveWhoIsInThisChatIDs removes the "who_is_in_this_chat" edge to Chat entities by IDs.
func (uu *UserUpdate) RemoveWhoIsInThisChatIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveWhoIsInThisChatIDs(ids...)
	return uu
}

// RemoveWhoIsInThisChat removes "who_is_in_this_chat" edges to Chat entities.
func (uu *UserUpdate) RemoveWhoIsInThisChat(c ...*Chat) *UserUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uu.RemoveWhoIsInThisChatIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uu.hooks) == 0 {
		if err = uu.check(); err != nil {
			return 0, err
		}
		affected, err = uu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uu.check(); err != nil {
				return 0, err
			}
			uu.mutation = mutation
			affected, err = uu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uu.hooks) - 1; i >= 0; i-- {
			if uu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uu *UserUpdate) check() error {
	if v, ok := uu.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	return nil
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   user.Table,
			Columns: user.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: user.FieldID,
			},
		},
	}
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Username(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldUsername,
		})
	}
	if value, ok := uu.mutation.Password(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldPassword,
		})
	}
	if uu.mutation.DoctorHasCertificationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorHasCertificationTable,
			Columns: []string{user.DoctorHasCertificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: certification.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedDoctorHasCertificationIDs(); len(nodes) > 0 && !uu.mutation.DoctorHasCertificationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorHasCertificationTable,
			Columns: []string{user.DoctorHasCertificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: certification.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.DoctorHasCertificationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorHasCertificationTable,
			Columns: []string{user.DoctorHasCertificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: certification.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserHasPInfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHasPInfoTable,
			Columns: []string{user.UserHasPInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pinfo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedUserHasPInfoIDs(); len(nodes) > 0 && !uu.mutation.UserHasPInfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHasPInfoTable,
			Columns: []string{user.UserHasPInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserHasPInfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHasPInfoTable,
			Columns: []string{user.UserHasPInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.DoctorScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorScheduleTable,
			Columns: []string{user.DoctorScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: schedule.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedDoctorScheduleIDs(); len(nodes) > 0 && !uu.mutation.DoctorScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorScheduleTable,
			Columns: []string{user.DoctorScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: schedule.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.DoctorScheduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorScheduleTable,
			Columns: []string{user.DoctorScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: schedule.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserHaveTelecomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTelecomsTable,
			Columns: []string{user.UserHaveTelecomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: telecom.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedUserHaveTelecomsIDs(); len(nodes) > 0 && !uu.mutation.UserHaveTelecomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTelecomsTable,
			Columns: []string{user.UserHaveTelecomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: telecom.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserHaveTelecomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTelecomsTable,
			Columns: []string{user.UserHaveTelecomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: telecom.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.DoctorRecordTreatmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorRecordTreatmentTable,
			Columns: []string{user.DoctorRecordTreatmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: treatment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedDoctorRecordTreatmentIDs(); len(nodes) > 0 && !uu.mutation.DoctorRecordTreatmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorRecordTreatmentTable,
			Columns: []string{user.DoctorRecordTreatmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: treatment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.DoctorRecordTreatmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorRecordTreatmentTable,
			Columns: []string{user.DoctorRecordTreatmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: treatment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserHaveTreatmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTreatmentTable,
			Columns: []string{user.UserHaveTreatmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: treatment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedUserHaveTreatmentIDs(); len(nodes) > 0 && !uu.mutation.UserHaveTreatmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTreatmentTable,
			Columns: []string{user.UserHaveTreatmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: treatment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserHaveTreatmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTreatmentTable,
			Columns: []string{user.UserHaveTreatmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: treatment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserHaveTokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTokenTable,
			Columns: []string{user.UserHaveTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: token.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedUserHaveTokenIDs(); len(nodes) > 0 && !uu.mutation.UserHaveTokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTokenTable,
			Columns: []string{user.UserHaveTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: token.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserHaveTokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTokenTable,
			Columns: []string{user.UserHaveTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: token.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserSendMessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserSendMessageTable,
			Columns: []string{user.UserSendMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: message.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedUserSendMessageIDs(); len(nodes) > 0 && !uu.mutation.UserSendMessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserSendMessageTable,
			Columns: []string{user.UserSendMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: message.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserSendMessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserSendMessageTable,
			Columns: []string{user.UserSendMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: message.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserSendNotificationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserSendNotificationTable,
			Columns: user.UserSendNotificationPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: notification.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedUserSendNotificationIDs(); len(nodes) > 0 && !uu.mutation.UserSendNotificationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserSendNotificationTable,
			Columns: user.UserSendNotificationPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: notification.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserSendNotificationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserSendNotificationTable,
			Columns: user.UserSendNotificationPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: notification.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.HasDepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.HasDepartmentTable,
			Columns: []string{user.HasDepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.HasDepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.HasDepartmentTable,
			Columns: []string{user.HasDepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.FromHospitalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.FromHospitalTable,
			Columns: []string{user.FromHospitalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: hospital.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.FromHospitalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.FromHospitalTable,
			Columns: []string{user.FromHospitalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: hospital.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserHaveDiseaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.UserHaveDiseaseTable,
			Columns: user.UserHaveDiseasePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: disease.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedUserHaveDiseaseIDs(); len(nodes) > 0 && !uu.mutation.UserHaveDiseaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.UserHaveDiseaseTable,
			Columns: user.UserHaveDiseasePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: disease.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserHaveDiseaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.UserHaveDiseaseTable,
			Columns: user.UserHaveDiseasePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: disease.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserHaveRoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.UserHaveRoleTable,
			Columns: user.UserHaveRolePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: role.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedUserHaveRoleIDs(); len(nodes) > 0 && !uu.mutation.UserHaveRoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.UserHaveRoleTable,
			Columns: user.UserHaveRolePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: role.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserHaveRoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.UserHaveRoleTable,
			Columns: user.UserHaveRolePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: role.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.WhoIsInThisChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.WhoIsInThisChatTable,
			Columns: user.WhoIsInThisChatPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chat.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedWhoIsInThisChatIDs(); len(nodes) > 0 && !uu.mutation.WhoIsInThisChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.WhoIsInThisChatTable,
			Columns: user.WhoIsInThisChatPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chat.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.WhoIsInThisChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.WhoIsInThisChatTable,
			Columns: user.WhoIsInThisChatPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chat.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUsername sets the "username" field.
func (uuo *UserUpdateOne) SetUsername(s string) *UserUpdateOne {
	uuo.mutation.SetUsername(s)
	return uuo
}

// SetPassword sets the "password" field.
func (uuo *UserUpdateOne) SetPassword(s string) *UserUpdateOne {
	uuo.mutation.SetPassword(s)
	return uuo
}

// AddDoctorHasCertificationIDs adds the "doctor_has_certification" edge to the Certification entity by IDs.
func (uuo *UserUpdateOne) AddDoctorHasCertificationIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddDoctorHasCertificationIDs(ids...)
	return uuo
}

// AddDoctorHasCertification adds the "doctor_has_certification" edges to the Certification entity.
func (uuo *UserUpdateOne) AddDoctorHasCertification(c ...*Certification) *UserUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uuo.AddDoctorHasCertificationIDs(ids...)
}

// AddUserHasPInfoIDs adds the "user_has_PInfo" edge to the PInfo entity by IDs.
func (uuo *UserUpdateOne) AddUserHasPInfoIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddUserHasPInfoIDs(ids...)
	return uuo
}

// AddUserHasPInfo adds the "user_has_PInfo" edges to the PInfo entity.
func (uuo *UserUpdateOne) AddUserHasPInfo(p ...*PInfo) *UserUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uuo.AddUserHasPInfoIDs(ids...)
}

// AddDoctorScheduleIDs adds the "doctor_schedule" edge to the Schedule entity by IDs.
func (uuo *UserUpdateOne) AddDoctorScheduleIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddDoctorScheduleIDs(ids...)
	return uuo
}

// AddDoctorSchedule adds the "doctor_schedule" edges to the Schedule entity.
func (uuo *UserUpdateOne) AddDoctorSchedule(s ...*Schedule) *UserUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return uuo.AddDoctorScheduleIDs(ids...)
}

// AddUserHaveTelecomIDs adds the "user_have_telecoms" edge to the Telecom entity by IDs.
func (uuo *UserUpdateOne) AddUserHaveTelecomIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddUserHaveTelecomIDs(ids...)
	return uuo
}

// AddUserHaveTelecoms adds the "user_have_telecoms" edges to the Telecom entity.
func (uuo *UserUpdateOne) AddUserHaveTelecoms(t ...*Telecom) *UserUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uuo.AddUserHaveTelecomIDs(ids...)
}

// AddDoctorRecordTreatmentIDs adds the "doctor_record_treatment" edge to the Treatment entity by IDs.
func (uuo *UserUpdateOne) AddDoctorRecordTreatmentIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddDoctorRecordTreatmentIDs(ids...)
	return uuo
}

// AddDoctorRecordTreatment adds the "doctor_record_treatment" edges to the Treatment entity.
func (uuo *UserUpdateOne) AddDoctorRecordTreatment(t ...*Treatment) *UserUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uuo.AddDoctorRecordTreatmentIDs(ids...)
}

// AddUserHaveTreatmentIDs adds the "user_have_treatment" edge to the Treatment entity by IDs.
func (uuo *UserUpdateOne) AddUserHaveTreatmentIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddUserHaveTreatmentIDs(ids...)
	return uuo
}

// AddUserHaveTreatment adds the "user_have_treatment" edges to the Treatment entity.
func (uuo *UserUpdateOne) AddUserHaveTreatment(t ...*Treatment) *UserUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uuo.AddUserHaveTreatmentIDs(ids...)
}

// AddUserHaveTokenIDs adds the "user_have_token" edge to the Token entity by IDs.
func (uuo *UserUpdateOne) AddUserHaveTokenIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddUserHaveTokenIDs(ids...)
	return uuo
}

// AddUserHaveToken adds the "user_have_token" edges to the Token entity.
func (uuo *UserUpdateOne) AddUserHaveToken(t ...*Token) *UserUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uuo.AddUserHaveTokenIDs(ids...)
}

// AddUserSendMessageIDs adds the "user_send_message" edge to the Message entity by IDs.
func (uuo *UserUpdateOne) AddUserSendMessageIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddUserSendMessageIDs(ids...)
	return uuo
}

// AddUserSendMessage adds the "user_send_message" edges to the Message entity.
func (uuo *UserUpdateOne) AddUserSendMessage(m ...*Message) *UserUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return uuo.AddUserSendMessageIDs(ids...)
}

// AddUserSendNotificationIDs adds the "user_send_notification" edge to the Notification entity by IDs.
func (uuo *UserUpdateOne) AddUserSendNotificationIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddUserSendNotificationIDs(ids...)
	return uuo
}

// AddUserSendNotification adds the "user_send_notification" edges to the Notification entity.
func (uuo *UserUpdateOne) AddUserSendNotification(n ...*Notification) *UserUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return uuo.AddUserSendNotificationIDs(ids...)
}

// SetHasDepartmentID sets the "has_department" edge to the Department entity by ID.
func (uuo *UserUpdateOne) SetHasDepartmentID(id int) *UserUpdateOne {
	uuo.mutation.SetHasDepartmentID(id)
	return uuo
}

// SetNillableHasDepartmentID sets the "has_department" edge to the Department entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableHasDepartmentID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetHasDepartmentID(*id)
	}
	return uuo
}

// SetHasDepartment sets the "has_department" edge to the Department entity.
func (uuo *UserUpdateOne) SetHasDepartment(d *Department) *UserUpdateOne {
	return uuo.SetHasDepartmentID(d.ID)
}

// SetFromHospitalID sets the "from_hospital" edge to the Hospital entity by ID.
func (uuo *UserUpdateOne) SetFromHospitalID(id int) *UserUpdateOne {
	uuo.mutation.SetFromHospitalID(id)
	return uuo
}

// SetNillableFromHospitalID sets the "from_hospital" edge to the Hospital entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableFromHospitalID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetFromHospitalID(*id)
	}
	return uuo
}

// SetFromHospital sets the "from_hospital" edge to the Hospital entity.
func (uuo *UserUpdateOne) SetFromHospital(h *Hospital) *UserUpdateOne {
	return uuo.SetFromHospitalID(h.ID)
}

// AddUserHaveDiseaseIDs adds the "user_have_disease" edge to the Disease entity by IDs.
func (uuo *UserUpdateOne) AddUserHaveDiseaseIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddUserHaveDiseaseIDs(ids...)
	return uuo
}

// AddUserHaveDisease adds the "user_have_disease" edges to the Disease entity.
func (uuo *UserUpdateOne) AddUserHaveDisease(d ...*Disease) *UserUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return uuo.AddUserHaveDiseaseIDs(ids...)
}

// AddUserHaveRoleIDs adds the "user_have_role" edge to the Role entity by IDs.
func (uuo *UserUpdateOne) AddUserHaveRoleIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddUserHaveRoleIDs(ids...)
	return uuo
}

// AddUserHaveRole adds the "user_have_role" edges to the Role entity.
func (uuo *UserUpdateOne) AddUserHaveRole(r ...*Role) *UserUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uuo.AddUserHaveRoleIDs(ids...)
}

// AddWhoIsInThisChatIDs adds the "who_is_in_this_chat" edge to the Chat entity by IDs.
func (uuo *UserUpdateOne) AddWhoIsInThisChatIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddWhoIsInThisChatIDs(ids...)
	return uuo
}

// AddWhoIsInThisChat adds the "who_is_in_this_chat" edges to the Chat entity.
func (uuo *UserUpdateOne) AddWhoIsInThisChat(c ...*Chat) *UserUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uuo.AddWhoIsInThisChatIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearDoctorHasCertification clears all "doctor_has_certification" edges to the Certification entity.
func (uuo *UserUpdateOne) ClearDoctorHasCertification() *UserUpdateOne {
	uuo.mutation.ClearDoctorHasCertification()
	return uuo
}

// RemoveDoctorHasCertificationIDs removes the "doctor_has_certification" edge to Certification entities by IDs.
func (uuo *UserUpdateOne) RemoveDoctorHasCertificationIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveDoctorHasCertificationIDs(ids...)
	return uuo
}

// RemoveDoctorHasCertification removes "doctor_has_certification" edges to Certification entities.
func (uuo *UserUpdateOne) RemoveDoctorHasCertification(c ...*Certification) *UserUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uuo.RemoveDoctorHasCertificationIDs(ids...)
}

// ClearUserHasPInfo clears all "user_has_PInfo" edges to the PInfo entity.
func (uuo *UserUpdateOne) ClearUserHasPInfo() *UserUpdateOne {
	uuo.mutation.ClearUserHasPInfo()
	return uuo
}

// RemoveUserHasPInfoIDs removes the "user_has_PInfo" edge to PInfo entities by IDs.
func (uuo *UserUpdateOne) RemoveUserHasPInfoIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveUserHasPInfoIDs(ids...)
	return uuo
}

// RemoveUserHasPInfo removes "user_has_PInfo" edges to PInfo entities.
func (uuo *UserUpdateOne) RemoveUserHasPInfo(p ...*PInfo) *UserUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uuo.RemoveUserHasPInfoIDs(ids...)
}

// ClearDoctorSchedule clears all "doctor_schedule" edges to the Schedule entity.
func (uuo *UserUpdateOne) ClearDoctorSchedule() *UserUpdateOne {
	uuo.mutation.ClearDoctorSchedule()
	return uuo
}

// RemoveDoctorScheduleIDs removes the "doctor_schedule" edge to Schedule entities by IDs.
func (uuo *UserUpdateOne) RemoveDoctorScheduleIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveDoctorScheduleIDs(ids...)
	return uuo
}

// RemoveDoctorSchedule removes "doctor_schedule" edges to Schedule entities.
func (uuo *UserUpdateOne) RemoveDoctorSchedule(s ...*Schedule) *UserUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return uuo.RemoveDoctorScheduleIDs(ids...)
}

// ClearUserHaveTelecoms clears all "user_have_telecoms" edges to the Telecom entity.
func (uuo *UserUpdateOne) ClearUserHaveTelecoms() *UserUpdateOne {
	uuo.mutation.ClearUserHaveTelecoms()
	return uuo
}

// RemoveUserHaveTelecomIDs removes the "user_have_telecoms" edge to Telecom entities by IDs.
func (uuo *UserUpdateOne) RemoveUserHaveTelecomIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveUserHaveTelecomIDs(ids...)
	return uuo
}

// RemoveUserHaveTelecoms removes "user_have_telecoms" edges to Telecom entities.
func (uuo *UserUpdateOne) RemoveUserHaveTelecoms(t ...*Telecom) *UserUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uuo.RemoveUserHaveTelecomIDs(ids...)
}

// ClearDoctorRecordTreatment clears all "doctor_record_treatment" edges to the Treatment entity.
func (uuo *UserUpdateOne) ClearDoctorRecordTreatment() *UserUpdateOne {
	uuo.mutation.ClearDoctorRecordTreatment()
	return uuo
}

// RemoveDoctorRecordTreatmentIDs removes the "doctor_record_treatment" edge to Treatment entities by IDs.
func (uuo *UserUpdateOne) RemoveDoctorRecordTreatmentIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveDoctorRecordTreatmentIDs(ids...)
	return uuo
}

// RemoveDoctorRecordTreatment removes "doctor_record_treatment" edges to Treatment entities.
func (uuo *UserUpdateOne) RemoveDoctorRecordTreatment(t ...*Treatment) *UserUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uuo.RemoveDoctorRecordTreatmentIDs(ids...)
}

// ClearUserHaveTreatment clears all "user_have_treatment" edges to the Treatment entity.
func (uuo *UserUpdateOne) ClearUserHaveTreatment() *UserUpdateOne {
	uuo.mutation.ClearUserHaveTreatment()
	return uuo
}

// RemoveUserHaveTreatmentIDs removes the "user_have_treatment" edge to Treatment entities by IDs.
func (uuo *UserUpdateOne) RemoveUserHaveTreatmentIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveUserHaveTreatmentIDs(ids...)
	return uuo
}

// RemoveUserHaveTreatment removes "user_have_treatment" edges to Treatment entities.
func (uuo *UserUpdateOne) RemoveUserHaveTreatment(t ...*Treatment) *UserUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uuo.RemoveUserHaveTreatmentIDs(ids...)
}

// ClearUserHaveToken clears all "user_have_token" edges to the Token entity.
func (uuo *UserUpdateOne) ClearUserHaveToken() *UserUpdateOne {
	uuo.mutation.ClearUserHaveToken()
	return uuo
}

// RemoveUserHaveTokenIDs removes the "user_have_token" edge to Token entities by IDs.
func (uuo *UserUpdateOne) RemoveUserHaveTokenIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveUserHaveTokenIDs(ids...)
	return uuo
}

// RemoveUserHaveToken removes "user_have_token" edges to Token entities.
func (uuo *UserUpdateOne) RemoveUserHaveToken(t ...*Token) *UserUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uuo.RemoveUserHaveTokenIDs(ids...)
}

// ClearUserSendMessage clears all "user_send_message" edges to the Message entity.
func (uuo *UserUpdateOne) ClearUserSendMessage() *UserUpdateOne {
	uuo.mutation.ClearUserSendMessage()
	return uuo
}

// RemoveUserSendMessageIDs removes the "user_send_message" edge to Message entities by IDs.
func (uuo *UserUpdateOne) RemoveUserSendMessageIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveUserSendMessageIDs(ids...)
	return uuo
}

// RemoveUserSendMessage removes "user_send_message" edges to Message entities.
func (uuo *UserUpdateOne) RemoveUserSendMessage(m ...*Message) *UserUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return uuo.RemoveUserSendMessageIDs(ids...)
}

// ClearUserSendNotification clears all "user_send_notification" edges to the Notification entity.
func (uuo *UserUpdateOne) ClearUserSendNotification() *UserUpdateOne {
	uuo.mutation.ClearUserSendNotification()
	return uuo
}

// RemoveUserSendNotificationIDs removes the "user_send_notification" edge to Notification entities by IDs.
func (uuo *UserUpdateOne) RemoveUserSendNotificationIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveUserSendNotificationIDs(ids...)
	return uuo
}

// RemoveUserSendNotification removes "user_send_notification" edges to Notification entities.
func (uuo *UserUpdateOne) RemoveUserSendNotification(n ...*Notification) *UserUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return uuo.RemoveUserSendNotificationIDs(ids...)
}

// ClearHasDepartment clears the "has_department" edge to the Department entity.
func (uuo *UserUpdateOne) ClearHasDepartment() *UserUpdateOne {
	uuo.mutation.ClearHasDepartment()
	return uuo
}

// ClearFromHospital clears the "from_hospital" edge to the Hospital entity.
func (uuo *UserUpdateOne) ClearFromHospital() *UserUpdateOne {
	uuo.mutation.ClearFromHospital()
	return uuo
}

// ClearUserHaveDisease clears all "user_have_disease" edges to the Disease entity.
func (uuo *UserUpdateOne) ClearUserHaveDisease() *UserUpdateOne {
	uuo.mutation.ClearUserHaveDisease()
	return uuo
}

// RemoveUserHaveDiseaseIDs removes the "user_have_disease" edge to Disease entities by IDs.
func (uuo *UserUpdateOne) RemoveUserHaveDiseaseIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveUserHaveDiseaseIDs(ids...)
	return uuo
}

// RemoveUserHaveDisease removes "user_have_disease" edges to Disease entities.
func (uuo *UserUpdateOne) RemoveUserHaveDisease(d ...*Disease) *UserUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return uuo.RemoveUserHaveDiseaseIDs(ids...)
}

// ClearUserHaveRole clears all "user_have_role" edges to the Role entity.
func (uuo *UserUpdateOne) ClearUserHaveRole() *UserUpdateOne {
	uuo.mutation.ClearUserHaveRole()
	return uuo
}

// RemoveUserHaveRoleIDs removes the "user_have_role" edge to Role entities by IDs.
func (uuo *UserUpdateOne) RemoveUserHaveRoleIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveUserHaveRoleIDs(ids...)
	return uuo
}

// RemoveUserHaveRole removes "user_have_role" edges to Role entities.
func (uuo *UserUpdateOne) RemoveUserHaveRole(r ...*Role) *UserUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uuo.RemoveUserHaveRoleIDs(ids...)
}

// ClearWhoIsInThisChat clears all "who_is_in_this_chat" edges to the Chat entity.
func (uuo *UserUpdateOne) ClearWhoIsInThisChat() *UserUpdateOne {
	uuo.mutation.ClearWhoIsInThisChat()
	return uuo
}

// RemoveWhoIsInThisChatIDs removes the "who_is_in_this_chat" edge to Chat entities by IDs.
func (uuo *UserUpdateOne) RemoveWhoIsInThisChatIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveWhoIsInThisChatIDs(ids...)
	return uuo
}

// RemoveWhoIsInThisChat removes "who_is_in_this_chat" edges to Chat entities.
func (uuo *UserUpdateOne) RemoveWhoIsInThisChat(c ...*Chat) *UserUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uuo.RemoveWhoIsInThisChatIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	var (
		err  error
		node *User
	)
	if len(uuo.hooks) == 0 {
		if err = uuo.check(); err != nil {
			return nil, err
		}
		node, err = uuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uuo.check(); err != nil {
				return nil, err
			}
			uuo.mutation = mutation
			node, err = uuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uuo.hooks) - 1; i >= 0; i-- {
			if uuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uuo *UserUpdateOne) check() error {
	if v, ok := uuo.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	return nil
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   user.Table,
			Columns: user.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: user.FieldID,
			},
		},
	}
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Username(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldUsername,
		})
	}
	if value, ok := uuo.mutation.Password(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldPassword,
		})
	}
	if uuo.mutation.DoctorHasCertificationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorHasCertificationTable,
			Columns: []string{user.DoctorHasCertificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: certification.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedDoctorHasCertificationIDs(); len(nodes) > 0 && !uuo.mutation.DoctorHasCertificationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorHasCertificationTable,
			Columns: []string{user.DoctorHasCertificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: certification.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.DoctorHasCertificationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorHasCertificationTable,
			Columns: []string{user.DoctorHasCertificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: certification.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserHasPInfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHasPInfoTable,
			Columns: []string{user.UserHasPInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pinfo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedUserHasPInfoIDs(); len(nodes) > 0 && !uuo.mutation.UserHasPInfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHasPInfoTable,
			Columns: []string{user.UserHasPInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserHasPInfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHasPInfoTable,
			Columns: []string{user.UserHasPInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.DoctorScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorScheduleTable,
			Columns: []string{user.DoctorScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: schedule.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedDoctorScheduleIDs(); len(nodes) > 0 && !uuo.mutation.DoctorScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorScheduleTable,
			Columns: []string{user.DoctorScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: schedule.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.DoctorScheduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorScheduleTable,
			Columns: []string{user.DoctorScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: schedule.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserHaveTelecomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTelecomsTable,
			Columns: []string{user.UserHaveTelecomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: telecom.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedUserHaveTelecomsIDs(); len(nodes) > 0 && !uuo.mutation.UserHaveTelecomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTelecomsTable,
			Columns: []string{user.UserHaveTelecomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: telecom.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserHaveTelecomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTelecomsTable,
			Columns: []string{user.UserHaveTelecomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: telecom.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.DoctorRecordTreatmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorRecordTreatmentTable,
			Columns: []string{user.DoctorRecordTreatmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: treatment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedDoctorRecordTreatmentIDs(); len(nodes) > 0 && !uuo.mutation.DoctorRecordTreatmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorRecordTreatmentTable,
			Columns: []string{user.DoctorRecordTreatmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: treatment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.DoctorRecordTreatmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DoctorRecordTreatmentTable,
			Columns: []string{user.DoctorRecordTreatmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: treatment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserHaveTreatmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTreatmentTable,
			Columns: []string{user.UserHaveTreatmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: treatment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedUserHaveTreatmentIDs(); len(nodes) > 0 && !uuo.mutation.UserHaveTreatmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTreatmentTable,
			Columns: []string{user.UserHaveTreatmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: treatment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserHaveTreatmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTreatmentTable,
			Columns: []string{user.UserHaveTreatmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: treatment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserHaveTokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTokenTable,
			Columns: []string{user.UserHaveTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: token.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedUserHaveTokenIDs(); len(nodes) > 0 && !uuo.mutation.UserHaveTokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTokenTable,
			Columns: []string{user.UserHaveTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: token.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserHaveTokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserHaveTokenTable,
			Columns: []string{user.UserHaveTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: token.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserSendMessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserSendMessageTable,
			Columns: []string{user.UserSendMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: message.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedUserSendMessageIDs(); len(nodes) > 0 && !uuo.mutation.UserSendMessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserSendMessageTable,
			Columns: []string{user.UserSendMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: message.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserSendMessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserSendMessageTable,
			Columns: []string{user.UserSendMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: message.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserSendNotificationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserSendNotificationTable,
			Columns: user.UserSendNotificationPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: notification.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedUserSendNotificationIDs(); len(nodes) > 0 && !uuo.mutation.UserSendNotificationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserSendNotificationTable,
			Columns: user.UserSendNotificationPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: notification.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserSendNotificationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserSendNotificationTable,
			Columns: user.UserSendNotificationPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: notification.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.HasDepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.HasDepartmentTable,
			Columns: []string{user.HasDepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.HasDepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.HasDepartmentTable,
			Columns: []string{user.HasDepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.FromHospitalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.FromHospitalTable,
			Columns: []string{user.FromHospitalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: hospital.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.FromHospitalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.FromHospitalTable,
			Columns: []string{user.FromHospitalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: hospital.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserHaveDiseaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.UserHaveDiseaseTable,
			Columns: user.UserHaveDiseasePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: disease.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedUserHaveDiseaseIDs(); len(nodes) > 0 && !uuo.mutation.UserHaveDiseaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.UserHaveDiseaseTable,
			Columns: user.UserHaveDiseasePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: disease.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserHaveDiseaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.UserHaveDiseaseTable,
			Columns: user.UserHaveDiseasePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: disease.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserHaveRoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.UserHaveRoleTable,
			Columns: user.UserHaveRolePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: role.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedUserHaveRoleIDs(); len(nodes) > 0 && !uuo.mutation.UserHaveRoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.UserHaveRoleTable,
			Columns: user.UserHaveRolePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: role.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserHaveRoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.UserHaveRoleTable,
			Columns: user.UserHaveRolePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: role.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.WhoIsInThisChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.WhoIsInThisChatTable,
			Columns: user.WhoIsInThisChatPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chat.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedWhoIsInThisChatIDs(); len(nodes) > 0 && !uuo.mutation.WhoIsInThisChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.WhoIsInThisChatTable,
			Columns: user.WhoIsInThisChatPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chat.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.WhoIsInThisChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.WhoIsInThisChatTable,
			Columns: user.WhoIsInThisChatPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chat.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
