// Code generated by entc, DO NOT EDIT.

package scheduletime

const (
	// Label holds the string label denoting the scheduletime type in the database.
	Label = "schedule_time"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStartTime holds the string denoting the starttime field in the database.
	FieldStartTime = "start_time"
	// FieldStopTime holds the string denoting the stoptime field in the database.
	FieldStopTime = "stop_time"
	// EdgeWhatTimeIsTheSchedule holds the string denoting the what_time_is_the_schedule edge name in mutations.
	EdgeWhatTimeIsTheSchedule = "what_time_is_the_schedule"
	// Table holds the table name of the scheduletime in the database.
	Table = "schedule_times"
	// WhatTimeIsTheScheduleTable is the table that holds the what_time_is_the_schedule relation/edge.
	WhatTimeIsTheScheduleTable = "schedule_times"
	// WhatTimeIsTheScheduleInverseTable is the table name for the Schedule entity.
	// It exists in this package in order to avoid circular dependency with the "schedule" package.
	WhatTimeIsTheScheduleInverseTable = "schedules"
	// WhatTimeIsTheScheduleColumn is the table column denoting the what_time_is_the_schedule relation/edge.
	WhatTimeIsTheScheduleColumn = "schedule_time_schedule"
)

// Columns holds all SQL columns for scheduletime fields.
var Columns = []string{
	FieldID,
	FieldStartTime,
	FieldStopTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "schedule_times"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"schedule_time_schedule",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
