// Code generated by entc, DO NOT EDIT.

package schedule

const (
	// Label holds the string label denoting the schedule type in the database.
	Label = "schedule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldActivity holds the string denoting the activity field in the database.
	FieldActivity = "activity"
	// FieldDetail holds the string denoting the detail field in the database.
	FieldDetail = "detail"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStartTime holds the string denoting the starttime field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the endtime field in the database.
	FieldEndTime = "end_time"
	// EdgeScheduleAppointment holds the string denoting the schedule_appointment edge name in mutations.
	EdgeScheduleAppointment = "schedule_appointment"
	// EdgeScheduleDoctor holds the string denoting the schedule_doctor edge name in mutations.
	EdgeScheduleDoctor = "schedule_doctor"
	// Table holds the table name of the schedule in the database.
	Table = "schedules"
	// ScheduleAppointmentTable is the table that holds the schedule_appointment relation/edge.
	ScheduleAppointmentTable = "appointments"
	// ScheduleAppointmentInverseTable is the table name for the Appointment entity.
	// It exists in this package in order to avoid circular dependency with the "appointment" package.
	ScheduleAppointmentInverseTable = "appointments"
	// ScheduleAppointmentColumn is the table column denoting the schedule_appointment relation/edge.
	ScheduleAppointmentColumn = "schedule_schedule_appointment"
	// ScheduleDoctorTable is the table that holds the schedule_doctor relation/edge.
	ScheduleDoctorTable = "schedules"
	// ScheduleDoctorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ScheduleDoctorInverseTable = "users"
	// ScheduleDoctorColumn is the table column denoting the schedule_doctor relation/edge.
	ScheduleDoctorColumn = "user_doctor_schedule"
)

// Columns holds all SQL columns for schedule fields.
var Columns = []string{
	FieldID,
	FieldActivity,
	FieldDetail,
	FieldStatus,
	FieldStartTime,
	FieldEndTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "schedules"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_doctor_schedule",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
